print(" ¿Preparad@ para aprender o repasar el lenguaje de programación que tú quieras?")
print(" - Recuerda que todas las instrucciones de participación están en el")
print("   repositorio de GitHub.")
print("*")
print(" Lo primero... ¿Ya has elegido un lenguaje?")
print(" - No todos son iguales, pero sus fundamentos suelen ser comunes.")
print(" - Este primer reto te servirá para familiarizarte con la forma de participar")
print("   enviando tus propias soluciones.")
print("*")
print(" EJERCICIO:")
print(" - Crea un comentario en el código y coloca la URL del sitio web oficial del")
print("   lenguaje de programación que has seleccionado.")
print(" - Representa las diferentes sintaxis que existen de crear comentarios")
print("   en el lenguaje (en una línea, varias...).")
print(" - Crea una variable (y una constante si el lenguaje lo soporta).")
print(" - Crea variables representando todos los tipos de datos primitivos")
print("   del lenguaje (cadenas de texto, enteros, booleanos...).")
print(' - Imprime por terminal el texto: "¡Hola, [y el nombre de tu lenguaje]!"')
print("*")
print(" ¿Fácil? No te preocupes, recuerda que esta es una ruta de estudio y")
print(" debemos comenzar por el principio.")